; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.41"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[ctools][version] = "1.9"

projects[context][version] = "3.6"

projects[context_mobile_switch][version] = "2.0-alpha1"

projects[facetapi][version] = "1.5"

projects[ds][version] = "2.11"

projects[entity][version] = "1.6"

projects[entityreference][version] = "1.1"

projects[facetapi_bonus][version] = "1.1"

projects[fivestar][version] = "2.1"

projects[flag][version] = "3.7"

projects[icomoon][version] = "1.0"

projects[icon][version] = "1.0-beta6"

projects[jquery_update][version] = "3.0-alpha3"

projects[libraries][version] = "2.2"

projects[mobile_switch][version] = "2.0-beta1"

projects[module_filter][version] = "2.0"

projects[search_api][version] = "1.16"

projects[search_api_db][version] = "1.5"

projects[search_api_ranges][version] = "1.5+9-dev"

projects[search_api_solr][version] = "1.9"

projects[views][version] = "3.11"

projects[views_calc][version] = "1.1"

projects[votingapi][version] = "2.12"

; Themes
projects[bootstrap][version] = "3.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[var][download][type] = ""
projects[var][download][url] = ""
projects[var][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[Mobile_Detect][download][type] = ""
libraries[Mobile_Detect][download][url] = ""
libraries[Mobile_Detect][directory_name] = "Mobile_Detect"
libraries[Mobile_Detect][type] = "library"
